AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    b1079390-712f-4d93-b4ff-555f5b956f19:
      size:
        width: 360
        height: 410
      position:
        x: 50
        'y': 290
      z: 0
      embeds:
        - 6c18f82b-a88f-41fc-9636-50e0b11482b3
        - db0820ab-772b-44ab-8094-d0212dd12d28
        - 337718d1-0381-461b-bb3a-1091dc21c77b
        - e30d239b-b3ea-4ffb-8d01-2c09354147cf
    e30d239b-b3ea-4ffb-8d01-2c09354147cf:
      size:
        width: 140
        height: 140
      position:
        x: 74.21905068296115
        'y': 358.48101303655676
      z: 1
      parent: b1079390-712f-4d93-b4ff-555f5b956f19
      embeds: []
      iscontainedinside:
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
    337718d1-0381-461b-bb3a-1091dc21c77b:
      size:
        width: 140
        height: 140
      position:
        x: 240
        'y': 360
      z: 1
      parent: b1079390-712f-4d93-b4ff-555f5b956f19
      embeds: []
      iscontainedinside:
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
    db0820ab-772b-44ab-8094-d0212dd12d28:
      size:
        width: 140
        height: 140
      position:
        x: 70
        'y': 530
      z: 1
      parent: b1079390-712f-4d93-b4ff-555f5b956f19
      embeds: []
      iscontainedinside:
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
    6c18f82b-a88f-41fc-9636-50e0b11482b3:
      size:
        width: 140
        height: 140
      position:
        x: 240
        'y': 530
      z: 1
      parent: b1079390-712f-4d93-b4ff-555f5b956f19
      embeds: []
      iscontainedinside:
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
        - b1079390-712f-4d93-b4ff-555f5b956f19
    2033d870-81b5-452d-8f46-d2be6c231f58:
      size:
        width: 60
        height: 60
      position:
        x: 70
        'y': 190
      z: 0
      embeds: []
    53e220ef-0dc3-40f2-a392-a18a91ae642b:
      source:
        id: b1079390-712f-4d93-b4ff-555f5b956f19
      target:
        id: 2033d870-81b5-452d-8f46-d2be6c231f58
      z: 0
Resources:
  vpcApSoutheast1ThreeTierStack:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: vpc-ap-southeast-1-d-three-tier-Stack
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b1079390-712f-4d93-b4ff-555f5b956f19
  publicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vpcApSoutheast1ThreeTierStack
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select 
        - 0
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: public-subnet-1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e30d239b-b3ea-4ffb-8d01-2c09354147cf
  publicSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vpcApSoutheast1ThreeTierStack
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select 
        - 1
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: public-subnet-2
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 337718d1-0381-461b-bb3a-1091dc21c77b
  privateSubnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vpcApSoutheast1ThreeTierStack
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select 
        - 0
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: private-subnet-3
    Metadata:
      'AWS::CloudFormation::Designer':
        id: db0820ab-772b-44ab-8094-d0212dd12d28
  privateSubnet4:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref vpcApSoutheast1ThreeTierStack
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select 
        - 1
        - 'Fn::GetAZs': !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: private-subnet-4
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 6c18f82b-a88f-41fc-9636-50e0b11482b3
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: InternetGatewayThreeTierStack
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 2033d870-81b5-452d-8f46-d2be6c231f58
  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref vpcApSoutheast1ThreeTierStack
      InternetGatewayId: !Ref InternetGateway
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 53e220ef-0dc3-40f2-a392-a18a91ae642b
